### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/databricks-scim-automation#100]
## Description

- As a developer, I would like to read the documentation to understand how the tool is designed and how download, build, and run the tool.

## Acceptance Criteria

Reference: [Definition of Done](../../docs/EngineeringPractices.md)

- [ ] Should have high-level architecture
- [ ] Should have flow/sequence type diagrams
- [ ] Should have a step-by-step setup and execution process
