### ISSUE TITLE
Databricks SCIM - CPR - September

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/databricks-scim-automation#12]
## Checkpoint Review

- M0, September
- September 10, 2010

### Demo

_Encouraged to just replay "best of" Sprint Demo_

- [x] Demo completed

### "DoneLog" Review

- [x] What was planned to be done this month?
  - Tech spike on Graph API calls
  - Tech spike on token refresh
  - Tech spike on using username/password to retrieve access token
  - Game Plan Review
- [x] What was actually done this month?
  - Tech spike on Graph API calls
  - Tech spike on token refresh
  - Setup scaffolding and CI/CD for original planned architecture
- [x] Changes in plan versus last
  - Planned on API approach; pivoted to CLI-based tool per Walmart Cloud ID team request.
- [x] Key design decisions and their outcomes
  - Using JavaScript/NPM for CLI tool
  - Planned on API approach based on Helium-Csharp
  - Engaged with AAD and DataBricks PG for long-term solution.
    - [Azure AD + DataBricks integration pptx](https://microsoft-my.sharepoint-df.com/:p:/r/personal/arvinh_microsoft_com/_layouts/15/guestaccess.aspx?e=ALyiKR&wdOrigin=TEAMS-ELECTRON.p2p.chiclet&wdExp=TEAMS-TREATMENT&share=Edz4bHG9myNMvl8q0WTXDtoBiU04KH5MkJT6W5n7XfnF5A)

### Key Project Risks and Concerns

- [x] Present Retro
  Issue #26 
- [x] Discuss open risks and mitigation plans
  - Cloud ID team rescinded approval for approach at last minute. Going forward the team will document all approvals and key decisions after calls in an email. In addition, the CSU team will create Jira tickets within the customer environment to track approval and ensure visibility throughout their org.

### Backlog Review

- [x] What is the planned for work in future sprints?
  - Complete CLI tool
  - Document tool usage
  - Customer code review & Handoff
- [x] Is additional checkpoint review needed?
  - N/A
- [x] Is additional Game Plan review needed?
  - Game Plan review was scheduled for 9/3. Cancelled after customer Cloud ID team rescinded support for the approach.
  - New Game Plan currently being created based on CLI approach
  - Key decision: publish this CLI tool to NPM?

### Tasks

- [x] Upload checkpoint review to Artifact Hub
