### ISSUE TITLE
Remove Terraform and update Readme

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/databricks-scim-automation#79]
## Tasks
- [ ] Remove infra folder
- [x] Remove CosmosDB URL check in code, replace with a different secret retrieval check
- [ ] Update docs to represent changes
