### ISSUE TITLE
SPIKE: Implement Microsoft Graph APIs

### ISSUE THREAD

**Issue by joheec** [retaildevcrews/databricks-scim-automation#9]
## Description
As a developer I want to implement Microsoft Graph APIs to validate the inputs and endpoints necessary to create a flow that creates as SCIM Sync Job

## Acceptance Criteria
- [] Identify endpoints necessary to create a SCIM Sync Job
- [] Validate the endpoints work as expected
- [] Identify the necessary user inputs to create a SCIM Sync Job
- [] Identify any endpoint nuances that need to be taken into consideration when building a flow (vs individual endpoint calls)

## Resources
- Files in Microsoft Teams > DataBricks SCIM > Files
    *  NEW-Databricks-SCIM-API-SampleOutputs.docx
    *  SCIM Provisioning.vsdx > SCIM Sequence++
    *  Walmart SCIM Automation Plan (Security v2 draft).pptx
- Spike notes in Microsoft Teams > DataBricks SCIM > Wiki

## Tasks
- [] Create an app service environment
- [] Create login code
- [] Create an access token
- [] Create a SCIM Connector Gallery App
- [] Get AAD Groups
- [] Get App Roles
- [] Add AAD Group to SCIM
- [] Create Sync Job
- [] Validate Credentials
- [] Save Credentials
- [] Start Sync Job
- [] Monitor Job
