### ISSUE TITLE
SCIM CLI Automation

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/databricks-scim-automation#96]
## Description

As a system administrator, I would like to execute a tool from the CLI that would automatically provision a single Databricks SCIM application.

## Acceptance Criteria

Reference: [Definition of Done](../../docs/EngineeringPractices.md)

- [ ] Should require explicit parameters
- [ ] Should print usage if parameters are missing or incorrect
- [ ] Should update the administrator on progress for each step
- [ ] Should produce an output log to a specified location
