### ISSUE TITLE
SCIM Tool Testing

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/databricks-scim-automation#98]
## Description

- As a developer, I would like to be able to create and run tests against the codebase to reduce the probability of introducing bugs.

## Acceptance Criteria

Reference: [Definition of Done](../../docs/EngineeringPractices.md)

- [ ] Should use a standard testing framework
- [ ] Should catch changes to signatures
- [ ] Should catch changes to processing based on deterministic input-output couples
