### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/databricks-scim-automation#99]
## Description

- As a user of the tool I would like to use the documentation to install, configure, and run the tool.

## Acceptance Criteria

Reference: [Definition of Done](../../docs/EngineeringPractices.md)

- [ ] Should document all of the required permissions for the user and the Application registration
- [ ] Should have a guided setup experience for provisioning the required resources needed to run the tool
- [ ] Should walk through how to retrieve and execute the tool
